@echo off
echo Seeding HealthcareReviewers table...

echo Inserting REV-001 - Dr. Sarah Mitchell (SENIOR)...
aws dynamodb put-item --table-name HealthcareReviewers --region us-east-2 --item "{\"reviewerId\":{\"S\":\"REV-001\"},\"name\":{\"S\":\"Dr. Sarah Mitchell\"},\"email\":{\"S\":\"s.mitchell@cms.gov\"},\"reviewerLevel\":{\"S\":\"SENIOR\"},\"currentWorkload\":{\"N\":\"2\"},\"maxConcurrentReviews\":{\"N\":\"5\"},\"avgReviewTimeMinutes\":{\"N\":\"45\"},\"approvalRate\":{\"N\":\"0.82\"},\"isAvailable\":{\"BOOL\":true},\"expertise\":{\"SS\":[\"medicare_advantage\",\"risk_adjustment\",\"premium_pricing\"]},\"updatedAt\":{\"S\":\"2026-07-01T08:00:00Z\"}}"

echo Inserting REV-002 - James Okafor (JUNIOR)...
aws dynamodb put-item --table-name HealthcareReviewers --region us-east-2 --item "{\"reviewerId\":{\"S\":\"REV-002\"},\"name\":{\"S\":\"James Okafor\"},\"email\":{\"S\":\"j.okafor@cms.gov\"},\"reviewerLevel\":{\"S\":\"JUNIOR\"},\"currentWorkload\":{\"N\":\"3\"},\"maxConcurrentReviews\":{\"N\":\"6\"},\"avgReviewTimeMinutes\":{\"N\":\"75\"},\"approvalRate\":{\"N\":\"0.71\"},\"isAvailable\":{\"BOOL\":true},\"expertise\":{\"SS\":[\"medicaid\",\"plan_benefits\",\"formulary\"]},\"updatedAt\":{\"S\":\"2026-07-01T08:00:00Z\"}}"

echo Inserting REV-003 - Dr. Linda Zhao (PRINCIPAL)...
aws dynamodb put-item --table-name HealthcareReviewers --region us-east-2 --item "{\"reviewerId\":{\"S\":\"REV-003\"},\"name\":{\"S\":\"Dr. Linda Zhao\"},\"email\":{\"S\":\"l.zhao@cms.gov\"},\"reviewerLevel\":{\"S\":\"PRINCIPAL\"},\"currentWorkload\":{\"N\":\"1\"},\"maxConcurrentReviews\":{\"N\":\"3\"},\"avgReviewTimeMinutes\":{\"N\":\"30\"},\"approvalRate\":{\"N\":\"0.91\"},\"isAvailable\":{\"BOOL\":true},\"expertise\":{\"SS\":[\"actuarial_review\",\"risk_adjustment\",\"compliance\",\"premium_pricing\"]},\"updatedAt\":{\"S\":\"2026-07-01T08:00:00Z\"}}"

echo Inserting REV-004 - Marcus Williams (SENIOR)...
aws dynamodb put-item --table-name HealthcareReviewers --region us-east-2 --item "{\"reviewerId\":{\"S\":\"REV-004\"},\"name\":{\"S\":\"Marcus Williams\"},\"email\":{\"S\":\"m.williams@cms.gov\"},\"reviewerLevel\":{\"S\":\"SENIOR\"},\"currentWorkload\":{\"N\":\"4\"},\"maxConcurrentReviews\":{\"N\":\"5\"},\"avgReviewTimeMinutes\":{\"N\":\"50\"},\"approvalRate\":{\"N\":\"0.78\"},\"isAvailable\":{\"BOOL\":true},\"expertise\":{\"SS\":[\"plan_benefits\",\"network_adequacy\",\"formulary\"]},\"updatedAt\":{\"S\":\"2026-07-01T08:00:00Z\"}}"

echo Inserting REV-005 - Emily Thornton (JUNIOR, unavailable)...
aws dynamodb put-item --table-name HealthcareReviewers --region us-east-2 --item "{\"reviewerId\":{\"S\":\"REV-005\"},\"name\":{\"S\":\"Emily Thornton\"},\"email\":{\"S\":\"e.thornton@cms.gov\"},\"reviewerLevel\":{\"S\":\"JUNIOR\"},\"currentWorkload\":{\"N\":\"5\"},\"maxConcurrentReviews\":{\"N\":\"6\"},\"avgReviewTimeMinutes\":{\"N\":\"90\"},\"approvalRate\":{\"N\":\"0.68\"},\"isAvailable\":{\"BOOL\":false},\"expertise\":{\"SS\":[\"medicaid\",\"eligibility\"]},\"updatedAt\":{\"S\":\"2026-07-01T08:00:00Z\"}}"

echo Inserting REV-006 - Dr. Robert Patel (PRINCIPAL)...
aws dynamodb put-item --table-name HealthcareReviewers --region us-east-2 --item "{\"reviewerId\":{\"S\":\"REV-006\"},\"name\":{\"S\":\"Dr. Robert Patel\"},\"email\":{\"S\":\"r.patel@cms.gov\"},\"reviewerLevel\":{\"S\":\"PRINCIPAL\"},\"currentWorkload\":{\"N\":\"2\"},\"maxConcurrentReviews\":{\"N\":\"3\"},\"avgReviewTimeMinutes\":{\"N\":\"25\"},\"approvalRate\":{\"N\":\"0.95\"},\"isAvailable\":{\"BOOL\":true},\"expertise\":{\"SS\":[\"actuarial_review\",\"compliance\",\"risk_adjustment\",\"fraud_detection\"]},\"updatedAt\":{\"S\":\"2026-07-01T08:00:00Z\"}}"

echo Inserting REV-007 - Angela Torres (SENIOR)...
aws dynamodb put-item --table-name HealthcareReviewers --region us-east-2 --item "{\"reviewerId\":{\"S\":\"REV-007\"},\"name\":{\"S\":\"Angela Torres\"},\"email\":{\"S\":\"a.torres@cms.gov\"},\"reviewerLevel\":{\"S\":\"SENIOR\"},\"currentWorkload\":{\"N\":\"1\"},\"maxConcurrentReviews\":{\"N\":\"5\"},\"avgReviewTimeMinutes\":{\"N\":\"40\"},\"approvalRate\":{\"N\":\"0.85\"},\"isAvailable\":{\"BOOL\":true},\"expertise\":{\"SS\":[\"network_adequacy\",\"formulary\",\"plan_benefits\"]},\"updatedAt\":{\"S\":\"2026-07-01T08:00:00Z\"}}"

echo Inserting REV-008 - Kevin Nakamura (JUNIOR)...
aws dynamodb put-item --table-name HealthcareReviewers --region us-east-2 --item "{\"reviewerId\":{\"S\":\"REV-008\"},\"name\":{\"S\":\"Kevin Nakamura\"},\"email\":{\"S\":\"k.nakamura@cms.gov\"},\"reviewerLevel\":{\"S\":\"JUNIOR\"},\"currentWorkload\":{\"N\":\"2\"},\"maxConcurrentReviews\":{\"N\":\"6\"},\"avgReviewTimeMinutes\":{\"N\":\"80\"},\"approvalRate\":{\"N\":\"0.73\"},\"isAvailable\":{\"BOOL\":true},\"expertise\":{\"SS\":[\"eligibility\",\"medicaid\",\"plan_benefits\"]},\"updatedAt\":{\"S\":\"2026-07-01T08:00:00Z\"}}"

echo Inserting REV-009 - Dr. Priya Sharma (SENIOR)...
aws dynamodb put-item --table-name HealthcareReviewers --region us-east-2 --item "{\"reviewerId\":{\"S\":\"REV-009\"},\"name\":{\"S\":\"Dr. Priya Sharma\"},\"email\":{\"S\":\"p.sharma@cms.gov\"},\"reviewerLevel\":{\"S\":\"SENIOR\"},\"currentWorkload\":{\"N\":\"3\"},\"maxConcurrentReviews\":{\"N\":\"5\"},\"avgReviewTimeMinutes\":{\"N\":\"55\"},\"approvalRate\":{\"N\":\"0.80\"},\"isAvailable\":{\"BOOL\":true},\"expertise\":{\"SS\":[\"risk_adjustment\",\"premium_pricing\",\"actuarial_review\"]},\"updatedAt\":{\"S\":\"2026-07-01T08:00:00Z\"}}"

echo Inserting REV-010 - Thomas Bergman (JUNIOR, at capacity)...
aws dynamodb put-item --table-name HealthcareReviewers --region us-east-2 --item "{\"reviewerId\":{\"S\":\"REV-010\"},\"name\":{\"S\":\"Thomas Bergman\"},\"email\":{\"S\":\"t.bergman@cms.gov\"},\"reviewerLevel\":{\"S\":\"JUNIOR\"},\"currentWorkload\":{\"N\":\"6\"},\"maxConcurrentReviews\":{\"N\":\"6\"},\"avgReviewTimeMinutes\":{\"N\":\"85\"},\"approvalRate\":{\"N\":\"0.69\"},\"isAvailable\":{\"BOOL\":false},\"expertise\":{\"SS\":[\"plan_benefits\",\"formulary\"]},\"updatedAt\":{\"S\":\"2026-07-01T08:00:00Z\"}}"

echo Inserting REV-011 - Dr. Claire Dupont (PRINCIPAL)...
aws dynamodb put-item --table-name HealthcareReviewers --region us-east-2 --item "{\"reviewerId\":{\"S\":\"REV-011\"},\"name\":{\"S\":\"Dr. Claire Dupont\"},\"email\":{\"S\":\"c.dupont@cms.gov\"},\"reviewerLevel\":{\"S\":\"PRINCIPAL\"},\"currentWorkload\":{\"N\":\"0\"},\"maxConcurrentReviews\":{\"N\":\"3\"},\"avgReviewTimeMinutes\":{\"N\":\"20\"},\"approvalRate\":{\"N\":\"0.97\"},\"isAvailable\":{\"BOOL\":true},\"expertise\":{\"SS\":[\"compliance\",\"fraud_detection\",\"actuarial_review\",\"risk_adjustment\",\"premium_pricing\"]},\"updatedAt\":{\"S\":\"2026-07-01T08:00:00Z\"}}"

echo Inserting REV-012 - Samuel Adeyemi (SENIOR)...
aws dynamodb put-item --table-name HealthcareReviewers --region us-east-2 --item "{\"reviewerId\":{\"S\":\"REV-012\"},\"name\":{\"S\":\"Samuel Adeyemi\"},\"email\":{\"S\":\"s.adeyemi@cms.gov\"},\"reviewerLevel\":{\"S\":\"SENIOR\"},\"currentWorkload\":{\"N\":\"0\"},\"maxConcurrentReviews\":{\"N\":\"5\"},\"avgReviewTimeMinutes\":{\"N\":\"42\"},\"approvalRate\":{\"N\":\"0.88\"},\"isAvailable\":{\"BOOL\":true},\"expertise\":{\"SS\":[\"medicare_advantage\",\"network_adequacy\",\"compliance\"]},\"updatedAt\":{\"S\":\"2026-07-01T08:00:00Z\"}}"

echo.
echo Done! 12 reviewers inserted.
