@echo off
echo Seeding HealthcareSubmissions table...

echo Inserting SUB-2024-001 - BlueCross Health Plans (PENDING)...
aws dynamodb put-item --table-name HealthcareSubmissions --region us-east-2 --item "{\"submissionId\":{\"S\":\"SUB-2024-001\"},\"organizationName\":{\"S\":\"BlueCross Health Plans\"},\"organizationId\":{\"S\":\"ORG-HC-00101\"},\"status\":{\"S\":\"PENDING\"},\"submittedAt\":{\"S\":\"2026-07-01T09:00:00Z\"},\"updatedAt\":{\"S\":\"2026-07-01T09:00:00Z\"},\"s3Bucket\":{\"S\":\"poc-stpfunctions-bucket\"},\"s3Key\":{\"S\":\"submissions/SUB-2024-001.txt\"},\"planType\":{\"S\":\"MEDICARE_ADVANTAGE\"}}"

echo Inserting SUB-2024-002 - Valley Health Insurance Co (PENDING)...
aws dynamodb put-item --table-name HealthcareSubmissions --region us-east-2 --item "{\"submissionId\":{\"S\":\"SUB-2024-002\"},\"organizationName\":{\"S\":\"Valley Health Insurance Co\"},\"organizationId\":{\"S\":\"ORG-HC-00202\"},\"status\":{\"S\":\"PENDING\"},\"submittedAt\":{\"S\":\"2026-07-01T09:15:00Z\"},\"updatedAt\":{\"S\":\"2026-07-01T09:15:00Z\"},\"s3Bucket\":{\"S\":\"poc-stpfunctions-bucket\"},\"s3Key\":{\"S\":\"submissions/SUB-2024-002.txt\"},\"planType\":{\"S\":\"MEDICAID\"}}"

echo Inserting SUB-2024-003 - Sunrise Medical Group (HUMAN_REVIEW)...
aws dynamodb put-item --table-name HealthcareSubmissions --region us-east-2 --item "{\"submissionId\":{\"S\":\"SUB-2024-003\"},\"organizationName\":{\"S\":\"Sunrise Medical Group\"},\"organizationId\":{\"S\":\"ORG-HC-00303\"},\"status\":{\"S\":\"HUMAN_REVIEW\"},\"submittedAt\":{\"S\":\"2026-06-30T10:00:00Z\"},\"updatedAt\":{\"S\":\"2026-06-30T10:45:00Z\"},\"assignedTo\":{\"S\":\"s.mitchell@cms.gov\"},\"s3Bucket\":{\"S\":\"poc-stpfunctions-bucket\"},\"s3Key\":{\"S\":\"submissions/SUB-2024-003.txt\"},\"planType\":{\"S\":\"MEDICARE_ADVANTAGE\"}}"

echo Inserting SUB-2024-004 - PacificCare Health Systems (APPROVED)...
aws dynamodb put-item --table-name HealthcareSubmissions --region us-east-2 --item "{\"submissionId\":{\"S\":\"SUB-2024-004\"},\"organizationName\":{\"S\":\"PacificCare Health Systems\"},\"organizationId\":{\"S\":\"ORG-HC-00404\"},\"status\":{\"S\":\"APPROVED\"},\"submittedAt\":{\"S\":\"2026-06-28T08:00:00Z\"},\"updatedAt\":{\"S\":\"2026-06-29T11:00:00Z\"},\"approvedAt\":{\"S\":\"2026-06-29T11:00:00Z\"},\"assignedTo\":{\"S\":\"AUTO_SYSTEM\"},\"s3Bucket\":{\"S\":\"poc-stpfunctions-bucket\"},\"s3Key\":{\"S\":\"submissions/SUB-2024-004.txt\"},\"planType\":{\"S\":\"MEDICAID\"}}"

echo Inserting SUB-2024-005 - Inland Empire Health Plan (AUTO_REJECT)...
aws dynamodb put-item --table-name HealthcareSubmissions --region us-east-2 --item "{\"submissionId\":{\"S\":\"SUB-2024-005\"},\"organizationName\":{\"S\":\"Inland Empire Health Plan\"},\"organizationId\":{\"S\":\"ORG-HC-00505\"},\"status\":{\"S\":\"AUTO_REJECT\"},\"submittedAt\":{\"S\":\"2026-06-29T14:00:00Z\"},\"updatedAt\":{\"S\":\"2026-06-29T14:30:00Z\"},\"assignedTo\":{\"S\":\"AUTO_SYSTEM\"},\"s3Bucket\":{\"S\":\"poc-stpfunctions-bucket\"},\"s3Key\":{\"S\":\"submissions/SUB-2024-005.txt\"},\"planType\":{\"S\":\"MEDICARE_ADVANTAGE\"}}"

echo Inserting SUB-2024-006 - Molina Healthcare Inc (PENDING)...
aws dynamodb put-item --table-name HealthcareSubmissions --region us-east-2 --item "{\"submissionId\":{\"S\":\"SUB-2024-006\"},\"organizationName\":{\"S\":\"Molina Healthcare Inc\"},\"organizationId\":{\"S\":\"ORG-HC-00606\"},\"status\":{\"S\":\"PENDING\"},\"submittedAt\":{\"S\":\"2026-07-01T11:00:00Z\"},\"updatedAt\":{\"S\":\"2026-07-01T11:00:00Z\"},\"s3Bucket\":{\"S\":\"poc-stpfunctions-bucket\"},\"s3Key\":{\"S\":\"submissions/SUB-2024-006.txt\"},\"planType\":{\"S\":\"MEDICAID\"}}"

echo Inserting SUB-2024-007 - Centene Corporation (HUMAN_REVIEW)...
aws dynamodb put-item --table-name HealthcareSubmissions --region us-east-2 --item "{\"submissionId\":{\"S\":\"SUB-2024-007\"},\"organizationName\":{\"S\":\"Centene Corporation\"},\"organizationId\":{\"S\":\"ORG-HC-00707\"},\"status\":{\"S\":\"HUMAN_REVIEW\"},\"submittedAt\":{\"S\":\"2026-06-30T13:00:00Z\"},\"updatedAt\":{\"S\":\"2026-06-30T13:50:00Z\"},\"assignedTo\":{\"S\":\"r.patel@cms.gov\"},\"s3Bucket\":{\"S\":\"poc-stpfunctions-bucket\"},\"s3Key\":{\"S\":\"submissions/SUB-2024-007.txt\"},\"planType\":{\"S\":\"MEDICARE_ADVANTAGE\"}}"

echo Inserting SUB-2024-008 - Aetna Better Health (APPROVED)...
aws dynamodb put-item --table-name HealthcareSubmissions --region us-east-2 --item "{\"submissionId\":{\"S\":\"SUB-2024-008\"},\"organizationName\":{\"S\":\"Aetna Better Health\"},\"organizationId\":{\"S\":\"ORG-HC-00808\"},\"status\":{\"S\":\"APPROVED\"},\"submittedAt\":{\"S\":\"2026-06-27T09:00:00Z\"},\"updatedAt\":{\"S\":\"2026-06-28T10:00:00Z\"},\"approvedAt\":{\"S\":\"2026-06-28T10:00:00Z\"},\"assignedTo\":{\"S\":\"AUTO_SYSTEM\"},\"s3Bucket\":{\"S\":\"poc-stpfunctions-bucket\"},\"s3Key\":{\"S\":\"submissions/SUB-2024-008.txt\"},\"planType\":{\"S\":\"MEDICAID\"}}"

echo Inserting SUB-2024-009 - HealthSpring of Tennessee (PENDING)...
aws dynamodb put-item --table-name HealthcareSubmissions --region us-east-2 --item "{\"submissionId\":{\"S\":\"SUB-2024-009\"},\"organizationName\":{\"S\":\"HealthSpring of Tennessee\"},\"organizationId\":{\"S\":\"ORG-HC-00909\"},\"status\":{\"S\":\"PENDING\"},\"submittedAt\":{\"S\":\"2026-07-01T12:30:00Z\"},\"updatedAt\":{\"S\":\"2026-07-01T12:30:00Z\"},\"s3Bucket\":{\"S\":\"poc-stpfunctions-bucket\"},\"s3Key\":{\"S\":\"submissions/SUB-2024-009.txt\"},\"planType\":{\"S\":\"MEDICARE_ADVANTAGE\"}}"

echo Inserting SUB-2024-010 - WellCare Health Plans (AUTO_REJECT)...
aws dynamodb put-item --table-name HealthcareSubmissions --region us-east-2 --item "{\"submissionId\":{\"S\":\"SUB-2024-010\"},\"organizationName\":{\"S\":\"WellCare Health Plans\"},\"organizationId\":{\"S\":\"ORG-HC-01010\"},\"status\":{\"S\":\"AUTO_REJECT\"},\"submittedAt\":{\"S\":\"2026-06-30T15:00:00Z\"},\"updatedAt\":{\"S\":\"2026-06-30T15:20:00Z\"},\"assignedTo\":{\"S\":\"AUTO_SYSTEM\"},\"s3Bucket\":{\"S\":\"poc-stpfunctions-bucket\"},\"s3Key\":{\"S\":\"submissions/SUB-2024-010.txt\"},\"planType\":{\"S\":\"MEDICAID\"}}"

echo.
echo Done! 10 submissions inserted.
