@echo off
echo Updating all reviewer emails to poreddy.manju@gmail.com...

echo Updating REV-001...
aws dynamodb update-item --table-name HealthcareReviewers --region us-east-2 --key "{\"reviewerId\":{\"S\":\"REV-001\"}}" --update-expression "SET email = :email" --expression-attribute-values "{\":email\":{\"S\":\"poreddy.manju@gmail.com\"}}"

echo Updating REV-002...
aws dynamodb update-item --table-name HealthcareReviewers --region us-east-2 --key "{\"reviewerId\":{\"S\":\"REV-002\"}}" --update-expression "SET email = :email" --expression-attribute-values "{\":email\":{\"S\":\"poreddy.manju@gmail.com\"}}"

echo Updating REV-003...
aws dynamodb update-item --table-name HealthcareReviewers --region us-east-2 --key "{\"reviewerId\":{\"S\":\"REV-003\"}}" --update-expression "SET email = :email" --expression-attribute-values "{\":email\":{\"S\":\"poreddy.manju@gmail.com\"}}"

echo Updating REV-004...
aws dynamodb update-item --table-name HealthcareReviewers --region us-east-2 --key "{\"reviewerId\":{\"S\":\"REV-004\"}}" --update-expression "SET email = :email" --expression-attribute-values "{\":email\":{\"S\":\"poreddy.manju@gmail.com\"}}"

echo Updating REV-005...
aws dynamodb update-item --table-name HealthcareReviewers --region us-east-2 --key "{\"reviewerId\":{\"S\":\"REV-005\"}}" --update-expression "SET email = :email" --expression-attribute-values "{\":email\":{\"S\":\"poreddy.manju@gmail.com\"}}"

echo Updating REV-006...
aws dynamodb update-item --table-name HealthcareReviewers --region us-east-2 --key "{\"reviewerId\":{\"S\":\"REV-006\"}}" --update-expression "SET email = :email" --expression-attribute-values "{\":email\":{\"S\":\"poreddy.manju@gmail.com\"}}"

echo Updating REV-007...
aws dynamodb update-item --table-name HealthcareReviewers --region us-east-2 --key "{\"reviewerId\":{\"S\":\"REV-007\"}}" --update-expression "SET email = :email" --expression-attribute-values "{\":email\":{\"S\":\"poreddy.manju@gmail.com\"}}"

echo Updating REV-008...
aws dynamodb update-item --table-name HealthcareReviewers --region us-east-2 --key "{\"reviewerId\":{\"S\":\"REV-008\"}}" --update-expression "SET email = :email" --expression-attribute-values "{\":email\":{\"S\":\"poreddy.manju@gmail.com\"}}"

echo Updating REV-009...
aws dynamodb update-item --table-name HealthcareReviewers --region us-east-2 --key "{\"reviewerId\":{\"S\":\"REV-009\"}}" --update-expression "SET email = :email" --expression-attribute-values "{\":email\":{\"S\":\"poreddy.manju@gmail.com\"}}"

echo Updating REV-010...
aws dynamodb update-item --table-name HealthcareReviewers --region us-east-2 --key "{\"reviewerId\":{\"S\":\"REV-010\"}}" --update-expression "SET email = :email" --expression-attribute-values "{\":email\":{\"S\":\"poreddy.manju@gmail.com\"}}"

echo Updating REV-011...
aws dynamodb update-item --table-name HealthcareReviewers --region us-east-2 --key "{\"reviewerId\":{\"S\":\"REV-011\"}}" --update-expression "SET email = :email" --expression-attribute-values "{\":email\":{\"S\":\"poreddy.manju@gmail.com\"}}"

echo Updating REV-012...
aws dynamodb update-item --table-name HealthcareReviewers --region us-east-2 --key "{\"reviewerId\":{\"S\":\"REV-012\"}}" --update-expression "SET email = :email" --expression-attribute-values "{\":email\":{\"S\":\"poreddy.manju@gmail.com\"}}"

echo.
echo Done! All 12 reviewer emails updated.
